name: Build KPM Module

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 获取源代码
        uses: actions/checkout@v4

      - name: 配置 Android NDK 环境
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c

      - name: 编译 KPM
        run: |
          # 严格按照官方文档，导出 NDK_PATH 环境变量
          export NDK_PATH=${{ steps.setup-ndk.outputs.ndk-path }}
          
          # 执行 make，并强制传入 NDK_PATH
          make NDK_PATH=$NDK_PATH

      - name: 打包并上传成品
        uses: actions/upload-artifact@v4
        with:
          name: KPM-Output
          path: |
            ./*.kpm
            out/*.kpm
            build/*.kpm
